name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2  # Cambiado a la versión 2 para evitar problemas con PNPM
      - name: Set up Node
        uses: actions/setup-node@v2  # Cambiado a la versión 2 para evitar problemas con PNPM
        with:
          node-version: 18
          cache: 'pnpm'  # Usar 'pnpm' en lugar de 'npm' como caché
      - name: Install dependencies
        run: pnpm install  # Usar 'pnpm' en lugar de 'npm'
      - name: Build
        run: pnpm run build  # Usar 'pnpm' en lugar de 'npm'
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-artifact@v2  # Actualizado a la versión 2 para evitar problemas con PNPM
        with:
          # Upload dist repository
          path: './dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
        with:
          # Especificar la rama de destino, por ejemplo, 'gh-pages'
          # Si tu rama de destino es 'gh-pages', cambia esto
          # según la rama que estés utilizando para GitHub Pages
          target_branch: gh-pages
