name: Deploy to GitHub Pages

on:
  # Runs on pushes targeting the default branch (main)
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js and pnpm
        uses: actions/setup-node@v2
        with:
          node-version: 16 # Puedes ajustar la versión de Node.js según tus necesidades
          cache: "pnpm" # Almacenar en caché las dependencias de pnpm

      - name: Install dependencies
        run: pnpm install # Instalar dependencias con pnpm

      - name: Build
        run: pnpm build # Ejecutar el comando de construcción con pnpm
        working-directory: ./ # Directorio de trabajo en la raíz del repositorio

      - name: Deploy to GitHub Pages
        run: |
          echo 'gh-pages' > .dist/.nojekyll
          git config --global user.name "TuNombreDeUsuario"
          git config --global user.email "tuemail@example.com"
          git add .
          git commit -m "Deploy via GitHub Actions"
          git push --force "https://${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git" main:main
