name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Cambia esto al nombre de tu rama principal

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16 # Puedes cambiar esto a tu versión de Node.js preferida

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Build
        run: |
          cd MUNDO-INFORMATICA  # Cambia al directorio de tu proyecto
          pnpm build

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name ${{ secrets.GITHUB_ACTOR }}
          git config --global user.email ${{ secrets.GITHUB_ACTOR }}@users.noreply.github.com
          echo 'your-gh-pages-branch-name' > .dist/.nojekyll  # Si necesitas deshabilitar Jekyll
          git add .
          git commit -m "Deploy via GitHub Actions"
          git push --force "https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" main:gh-pages
