name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Set Git User
        run: |
          git config --global user.name "Nataniel44"
          git config --global user.email "josenatanielsoto@gmail.com"

      - name: Build
        run: |
          pnpm install
          pnpm build
        working-directory: ./ # Directorio de trabajo en la raíz del repositorio

      - name: Create .dist directory
        run: mkdir -p .dist

      - name: Create .nojekyll file
        run: echo 'gh-pages' > .dist/.nojekyll

      - name: Deploy to GitHub Pages
        run: |
          git add .
          git commit -m "Deploy via GitHub Actions"
          git push --force "https://@github.com/Nataniel44/MUNDO-INFORMATICA.git" main:gh-pages
