name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Set Git User
        run: |
          git config --global user.name "TuNombreDeUsuario"
          git config --global user.email "tu@email.com"

      - name: Build
        run: |
          pnpm install
          pnpm build
        working-directory: ./ # Directorio de trabajo en la raíz del repositorio

      - name: Deploy to GitHub Pages
        run: |
          echo 'gh-pages' > .dist/.nojekyll
          git add .
          git commit -m "Deploy via GitHub Actions"
          git push --force "https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" main:gh-pages
