name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Cambia 'main' al nombre de tu rama principal si es diferente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

     - name: Deploy to GitHub Pages
  uses: JamesIves/github-pages-deploy-action@4.1.4
  with:
    branch: gh-pages # Puedes cambiar esta rama si lo deseas
    folder: build # Aquí debe estar la carpeta correcta, sin corchetes de cierre

